server:
  port: 8099
  servlet:
    contextPath: /badminton
  error:
    whitelabel:
      enabled: false
spring:
  application:
    name: badminton_pairing
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  resources:
    static-locations: file:/Users/chenyifan/Documents/workspace-fan/badmintonPairing/src/main/resources/static/
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    cache: true
    prefix: file:/Users/chenyifan/Documents/workspace-fan/badmintonPairing/src/main/resources/templates/
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail-username}
    password: ${mail-password}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    user:
      name: ${db-username}
      password: ${db-password}
  crawler:
    email: ${crawler-username}
    password: ${crawler-password}
  redis:
    host: ${vm-port}           # Redis 服務器的主機名或 IP 地址
    port: 6379                 # Redis 服務器的端口號
    password: ${db-password}   # Redis 的密碼（如果有設定）
    ssl: false                 # 是否啟用 SSL（預設為 false）
  data:
    mongodb:
      uri: mongodb://${db-username}:${db-password}@${vm-port}:27017
  elasticsearch:
    hostname: localhost
    port: 9200
    connection-timeout: 3000
    username: ${db-username}
    password: ${db-password}

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

google:
  client:
    id: ${google-client-id}
    secret: ${google-client-secret}
  redirect:
    uri: http://localhost:8099/badminton/oauth2/callback

line:
  bot:
    channel:
      access:
        token: ${channel-access-token}
      secret: ${channel-access-secret}

config:
  jsonPath: /Users/chenyifan/Documents/workspace-fan/badmintonPairing/src/main/resources/static/js/
  picture_path: /Users/chenyifan/Documents/workspace-fan/picture/badminton_images/
  globalDomain: http://localhost:8099/badminton/
  crawlerDomain: http://localhost:5000/badminton/
  picSavePath: /Users/chenyifan/Documents/workspace-fan/badmintonPairing/badminton_images/
  picShowPath: http://localhost:8099/badminton/badminton_images/
  fileSavePath: /Users/chenyifan/Documents/workspace-fan/badmintonPairing/badminton_files/
  fileShowPath: http://localhost:8099/badminton/badminton_files/
  gptBackupSavePath: /Users/chenyifan/Documents/workspace-fan/badmintonPairing/badminton_files/backup/
  apiKey: ${openai-api-key}
  channelAccessToken: ${channel-access-token}
