server:
  port: 8080
  address: 0.0.0.0
  servlet:
    contextPath: /badminton
  error:
    whitelabel:
      enabled: false
spring:
  application:
    name: badminton_pairing
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  resources:
    static-locations: file:/opt/badmintonPairing/static/
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    cache: true
    prefix: file:/opt/badmintonPairing/templates/
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail-username}
    password: ${mail-password}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    user:
      name: yifan
      password: password
  crawler:
    email: ${crawler-username}
    password: ${crawler-password}
  redis:
    host: 127.0.0.1            # Redis 服務器的主機名或 IP 地址
    port: 6379                 # Redis 服務器的端口號
    password: ${db-password}   # Redis 的密碼（如果有設定）
    ssl: false                 # 是否啟用 SSL（預設為 false）
  data:
    mongodb:
      uri: mongodb://${db-username}:${db-password}@localhost:27017

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

google:
  client:
    id: ${google-client-id}
    secret: ${google-client-secret}
  redirect:
    uri: https://gurula.cc/badminton/oauth2/callback

line:
  bot:
    channel:
      access:
        token: ${channel-access-token}
      secret: ${channel-access-secret}

config:
  jsonPath: /opt/badmintonPairing/static/js/
  picture_path: /opt/badmintonPairing/badminton_images/
  globalDomain: https://gurula.cc/badminton/
  crawlerDomain: http://localhost:5000/badminton/
  picSavePath: /opt/badmintonPairing/badminton_images/
  picShowPath: https://gurula.cc/badminton/badminton_images/
  fileSavePath: /opt/badmintonPairing/badminton_files/
  fileShowPath: https://gurula.cc/badminton/badminton_files/
  gptBackupSavePath: /opt/badmintonPairing/badminton_files/backup/
  apiKey: ${openai-api-key}
  channelAccessToken: ${channel-access-token}